### ISSUE TITLE
Avoid caching AWS credentials in the filesystem

### ISSUE THREAD

**Issue by nvalentine-puppetlabs** [puppetlabs/puppetlabs-aws#139]
It would be great if there was a way for the Types + Providers to access AWS credentials without the module user having to find a way to safely export AWS_* into the shell environment nor caching the information in ~/.aws/credentials. Perhaps the creds passwed in as a parameter of the base class, stored in mprotect()'ed memory, and then the Providers having some internal contract as to where they can go in memory to get at that data?

**Comment by garethr** [comment]
I think the preferred way of securely dealing with credentials in AWS is to avoid doing so and use IAM (http://aws.amazon.com/iam/). We have a [full profile described in the examples](https://github.com/puppetlabs/puppetlabs-aws/tree/master/examples/iam-profile). This will be easy to do once https://github.com/puppetlabs/puppetlabs-aws/pull/59 is merged in.

More generally I think this is a broader secret management issue for Puppet, given that and the above note about IAM I'm going to close this issue.

**Comment by daveseff** [comment]
Damn. I missed this thread. I would have suggested maybe hiera/eyaml for storing aws keys.

**Comment by garethr** [comment]
@daveseff you can use `hiera-eyaml` if you chose, we should probably include an example of doing that. Ultimately you would use it to drop an AWS configuration file onto disk. The problem there is you still end up with unencrypted credentials on the host which needs them, which is why IAM is a better solution if you're in AWS. The main difference is, in the case of a machine compromise:

* a box with IAM permissions allows for making requests, but you can't transfer the credentials elsewhere. If I shut down the box you lose your ability to exploit
* a box with a credentials file means, as an attacker, I can take those credentials and use them wherever I like (unless you've been good and placed a ip address Condition on the IAM profile)

Ultimately credentials are worth avoiding if you can. If you can't then `hiera-eyaml` is a good way to go, combined with an IAM role with IP restrictions.
