### ISSUE TITLE
Support multiple resources with the same EC2 name

### ISSUE THREAD

**Issue by rfletcher** [puppetlabs/puppetlabs-aws#172]
AWS supports like-named security groups in different regions, but I can't find a way to manage them using puppetlabs-aws. I expected something like this to work:

````puppet
ec2_securitygroup { "us-east-1 group-a":
  name        => 'group-a',
  description => 'a security group',
  region      => 'us-east-1',
}
ec2_securitygroup { "us-west-2 group-a":
  name        => 'group-a',
  description => 'a security group',
  region      => 'us-west-2',
}
````

But `name` is the resource namevar, so it results in this error:

> Error: Puppet::Parser::AST::Resource failed with error ArgumentError:
> Cannot alias Ec2_securitygroup[us-west-2 group-a] to ["group-a"] ...
> resource ["Ec2_securitygroup", "group-a"] already declared

I tried to work around the issue by passing a `tags` hash with `Name` specified, but that failed too. I've tested this on master @44b0b31f.

Is it possible to manage like-named groups in multiple regions?

**Comment by rfletcher** [comment]
I've since learned this is a more general problem. For example, it also appears to be impossible to create two instances called 'nat' in separate VPCs, even when the Puppet resource names are different:

> Cannot alias Ec2_instance[vpc2-nat] to ["nat"] ... resource ["Ec2_instance", "nat"] already declared

I've renamed the issue to reflect the general case.

For now I'll probably just `puppet apply` separate manifests for each region/vpc, so the same-named resources are in separate Puppet catalogs. I'm all ears if someone can think of a better workaround.

**Comment by garethr** [comment]
@rfletcher thanks for reporting. I'd like to write this up in more detail when I get a moment, this is more a design feature of the current implementation.

The module relies heavily on auto-required resources, these help with ensuring everything happens in the correct order. So for instance for instances when you say `security_groups => ['this-group']` you know it's also the puppet resource with the name `this-group`.

This has the downside you describe in that now resources have to be unique across AWS, which isn't a constraint Amazon make.

We might consider changes here in the future if a suitable pattern emerges, for the moment I'll close this issue as by design. Hope that makes sense? If not please do reopen and happy to discuss ideas/trade-offs.

**Comment by rfletcher** [comment]
Thanks for following up. I totally understand why it works this way today, and that it's not an easy change. I'm still hoping a future version works around this constraint on the puppet-aws module side though, so I don't have to work around it in my manifests.
