### ISSUE TITLE
Add the ability to add cypher, SSL certificate, and the ability to configure health check params

### ISSUE THREAD

**Issue by daveseff** [puppetlabs/puppetlabs-aws#214]
I need something like:
`
elb_loadbalancer { "my-elb" :
# Feature Request

```
    ensure               => present,
    region               => 'us-east-1',

    instances            => ['host1', 'host2',],
    security_groups      => ['my-sg'],
    subnets              => ['public'],
    scheme               => 'internet-facing',
    health_check   => {
        target => "HTTP:80/index.php",
        timeout    => 25,
        interval    => 30,
        unhealthy_threshold  => 2,
        healthy_threshold  => 3,
    }
    listeners            => [
      { protocol => 'TCP', 
        load_balancer_port => '80',  
        instance_protocol => 'TCP', 
        instance_port  => '80', },
      { protocol => 'TCP', 
        load_balancer_port => '443', 
        instance_protocol => 'TCP', 
        ssl_certificate => 'mysitescert.com',
        cypher => 'ELBSecurityPolicy-2015-05',
        instance_port  => '8080', },
    ],
  }
```

`

**Comment by ahenroid** [comment]
@daveseff, this was partially address by #215. Should I leave this issue open?

**Comment by zleswomp** [comment]
#387 and #408 also facilitated what is requested in this issue.  The policy contents are managed, in place of specifying the name of the policy to use.  The name is actually useless, since it pertains only to the ELB in target.  That is to say, two policies may exist under the same name with different contents and be attached to two different ELBs.  In any case, we are leveraging this work, managing the policies, certificates (ACM and IAM) and health checks.  This is resolved from my perspective.
