### ISSUE TITLE
Always prefetching!

### ISSUE THREAD

**Issue by DoctahPopp871** [puppetlabs/puppetlabs-aws#226]
I have started to experience intermittent failures of the aws module due to prefetch errors. 

Error: Failed to apply catalog: undefined local variable or method `region' for Puppet::Type::Route53_cname_record::ProviderV2:Class

Running a puppet agent -t --trace --debug shows that the prefetch takes place prior to checking for any aws resources. Is there anyway to limit the need to prefetch values especially something like region which will remain static in most cases. A single prefetch at time of catalog compile seems reasonable.

**Comment by garethr** [comment]
This issue may be a number of things but the error reporting was broken. That's now fixed with https://github.com/puppetlabs/puppetlabs-aws/commit/11a3640167892eb41e2fd278c2e914a79d5852a4 which will be in a release soon. That should expose the real issue.

If you have a large number of domains this might be triggered by rate limiting, in which case it's worth talking to Amazon as they might be able to adjust this.

Do provide the error with this issue and any data you have, we're always interested in further optimising the queries we're making.
